security:
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        users:
            entity:
                class: App\Entity\User

        organizations:
            entity:
                class: App\Entity\Organization

    encoders:
        Symfony\Component\Security\Core\User\UserInterface:
            algorithm: auto

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        organizations:
            pattern: ^/organizations
            anonymous: lazy
            provider: organizations
            guard:
                authenticators:
                    - App\Security\OrganizationLoginFormAuthenticator

            logout:
                path: app_organization_logout
                target: app_organization_index

            remember_me:
                name: remember_me_organization
                secret:   '%kernel.secret%'
                lifetime: 604800 # 1 week in seconds
                path:     /

        main:
            anonymous: lazy
            provider: users
            guard:
                authenticators:
                    - App\Security\UserLoginFormAuthenticator

            logout:
                path: app_logout
                target: user_home

            remember_me:
                name: remember_me_user
                secret:   '%kernel.secret%'
                lifetime: 604800 # 1 week in seconds
                path:     /

    access_control:
        - { path: ^/(user\/new|login|organizations\/login)$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/organizations, roles: ROLE_ORGANIZATION }
        - { path: ^/, roles: ROLE_USER }
