image:
  name: docker/compose:1.25.0 # https://github.com/docker/compose/blob/master/Dockerfile
  entrypoint: ["/bin/sh", "-c"]

services:
  - docker:dind

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2
  GIT_SUBMODULE_STRATEGY: none
  COMPOSE_HTTP_TIMEOUT: 120
  COMPOSE_PROJECT_NAME: "app_${CI_JOB_ID}"

before_script:
  - command -v docker > /dev/null 2>&1 && docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  - test -f docker-compose.override.ci.yml.dist && cp docker-compose.override.ci.yml.dist docker-compose.override.yml

stages:
  - prepare
  - test
  - build
  - deploy

prepare:
  stage: prepare
  script:
    - docker pull ${CI_REGISTRY_IMAGE}/php-flex-dev:latest || true
    - docker build --pull -t ${CI_REGISTRY_IMAGE}/php-flex-dev:latest --cache-from ${CI_REGISTRY_IMAGE}/php-flex-dev:latest -f docker/php-flex/Dockerfile --target withoutsources .
    - docker push ${CI_REGISTRY_IMAGE}/php-flex-dev:latest
  when: manual
  only:
    - master

.build:
  stage: build
  script:
    - apk add --no-cache git
    - export BUILD_TAG=$(git describe --tags)
    - echo "Building image ${BUILD_TAG}"
    - docker pull ${CI_REGISTRY_IMAGE}/php-flex-dev:latest || true
    - docker pull ${CI_REGISTRY_IMAGE}/fpm:latest || true
    - docker pull ${CI_REGISTRY_IMAGE}/nginx:latest || true
    - docker build -t ${CI_REGISTRY_IMAGE}/fpm:${CI_COMMIT_REF_SLUG} -t ${CI_REGISTRY_IMAGE}/fpm:latest --cache-from ${CI_REGISTRY_IMAGE}/php-flex-dev:latest --cache-from ${CI_REGISTRY_IMAGE}/fpm:latest -f docker/php-flex/Dockerfile --target withsources-fpm --build-arg BUILD_TAG=${BUILD_TAG} .
    - docker run --rm -v $(pwd):/host ${CI_REGISTRY_IMAGE}/fpm:latest mv -f /srv/public/build /host/public
    - docker build -t ${CI_REGISTRY_IMAGE}/nginx:${CI_COMMIT_REF_SLUG} -t ${CI_REGISTRY_IMAGE}/nginx:latest --cache-from ${CI_REGISTRY_IMAGE}/nginx:latest -f docker/nginx/Dockerfile --target withsources .
    - docker push ${CI_REGISTRY_IMAGE}/fpm:${CI_COMMIT_REF_SLUG}
    - docker push ${CI_REGISTRY_IMAGE}/fpm:latest
    - docker push ${CI_REGISTRY_IMAGE}/nginx:${CI_COMMIT_REF_SLUG}
    - docker push ${CI_REGISTRY_IMAGE}/nginx:latest

build:master:
  extends: .build
  only:
    - master

build:tag:
  extends: .build
  after_script:
    - test -z "$CI_COMMIT_TAG" && echo "This is not a tag pipeline" && exit 1
    - echo "Tag => $CI_COMMIT_TAG"
    - git fetch -aq
    - git branch -a --contains $(git rev-list -n 1 ${CI_COMMIT_TAG}) --format "%(refname:short)" | grep '^origin/master$' || (echo "The tag is not present on master" && exit 1)
    - docker tag ${CI_REGISTRY_IMAGE}/fpm:${CI_COMMIT_REF_SLUG} ${CI_REGISTRY_IMAGE}/fpm:release-latest && docker push ${CI_REGISTRY_IMAGE}/fpm:release-latest
    - docker tag ${CI_REGISTRY_IMAGE}/nginx:${CI_COMMIT_REF_SLUG} ${CI_REGISTRY_IMAGE}/nginx:release-latest && docker push ${CI_REGISTRY_IMAGE}/nginx:release-latest
  only:
    - /^\d+\.\d+(?:\.\d+)?$/
  except:
    - branches

deploy:snapshot:
  stage: deploy
  variables:
    GIT_STRATEGY: fetch
  dependencies: []
  script:
    - apk add --no-cache curl
    - curl --request POST --form "token=$CI_JOB_TOKEN" --form ref=master https://gitlab.com/api/v4/projects/7280731/trigger/pipeline
  only:
    - master
